import { Page } from "@playwright/test";

export class HomePage {
  readonly homePageLogo: string;
  readonly homePageLogoImage: string;
  readonly navbarHome: string;
  readonly navbarContact: string;
  readonly navbarAbout: string;
  readonly navbarCart: string;
  readonly navbarLogin: string;
  readonly navbarSignup: string;
  readonly navLogoutButton: string;
  readonly navWelcome: string;
  readonly navItems: string;
  readonly categoriesHeader: string;
  readonly categoriesPhones: string;
  readonly categoriesLaptops: string;
  readonly categoriesMonitors: string;
  readonly firstProductCardTitle: string;
  readonly secondProductCardTitle: string;
  readonly paginationPreviousButton: string;
  readonly paginationNextButton: string;
  readonly firstProductImage: string;
  readonly secondProductImage: string;
  readonly carousel: string;
  readonly carouselImages: string;
  readonly activeCarouselImage: string;
  readonly carouselNextButton: string;
  readonly carouselPreviousButton: string;
  readonly footer: string;
  readonly footerHeaderAboutUsText: string;
  readonly footerHeaderGetInTouchText: string;
  readonly footerCopyrightText: string;
  readonly productContainer: string;
  readonly productTitles: string;
  readonly productPrices: string;
  readonly productImages: string;
  readonly productDescriptions: string;

  constructor(page: Page) {
    this.homePageLogo = `css=nav[id='narvbarx'] a[id='nava']`;
    this.homePageLogoImage = `css=nav[id='narvbarx'] a[id='nava'] img`;
    this.navbarHome = `css=ul[class='navbar-nav ml-auto'] li[class='nav-item active'] a[href='index.html']`;
    this.navbarContact = `css=a[data-target='#exampleModal']`;
    this.navbarAbout = `css=a[data-target='#videoModal']`;
    this.navbarCart = `css=a[id='cartur']`;
    this.navbarLogin = `css=a[id='login2']`;
    this.navbarSignup = `css=a[id='signin2']`;
    this.navLogoutButton = `css=a[id='logout2']`;
    this.navWelcome = `css=a[id='nameofuser']`;
    this.navItems = `css= div[id="navbarExample"] ul[class="navbar-nav ml-auto"] li`;
    this.categoriesHeader = `css=div[class='list-group'] a[id='cat']`;
    this.categoriesPhones = `xpath=//a[@id='itemc' and text()='Phones']`;
    this.categoriesLaptops = `xpath=//a[@id='itemc' and text()='Laptops']`;
    this.categoriesMonitors = `xpath=//a[@id='itemc' and text()='Monitors']`;
    this.firstProductCardTitle = `css=div[id='tbodyid'] div:nth-child(1) div:nth-child(1) div:nth-child(2) h4:nth-child(1) a`;
    this.secondProductCardTitle = `css=div[id='tbodyid'] div:nth-child(2) div:nth-child(1) div:nth-child(2) h4:nth-child(1) a`;
    this.paginationPreviousButton = `css=li[class='page-item'] button[id='prev2']`;
    this.paginationNextButton = `css=li[class='page-item'] button[id='next2']`;
    this.firstProductImage = `css=div[id='tbodyid'] div:nth-child(1) div:nth-child(1) a:nth-child(1) img:nth-child(1)`;
    this.secondProductImage = `css=div[id='tbodyid'] div:nth-child(2) div:nth-child(1) a:nth-child(1) img:nth-child(1)`;
    this.carousel = `css=div[id='contcar'] div[id='carouselExampleIndicators']`;
    this.carouselImages = `css=div[class='carousel-inner'] div img`;
    this.activeCarouselImage = `css=.carousel-item.active img`;
    this.carouselNextButton = `css=a[data-slide='next'] span[class='carousel-control-next-icon']`;
    this.carouselPreviousButton = `css=a[data-slide='prev'] span[class='carousel-control-prev-icon']`;
    this.footer = `css=div[id='footc']`;
    this.footerHeaderAboutUsText = `css=div[class='col-sm-4 col-lg-4 col-md-4'] b`;
    this.footerHeaderGetInTouchText = `css=div[class='col-sm-3 col-lg-3 col-md-3'] b`;
    this.footerCopyrightText = `xpath=//p[@class='m-0 text-center text-white']`;
    this.productContainer = `css=div[id='tbodyid'] div[class='col-lg-4 col-md-6 mb-4'] div[class='card h-100']`;
    this.productTitles = `css=div[id='tbodyid'] div[class='col-lg-4 col-md-6 mb-4'] div[class='card-block'] a`;
    this.productPrices = `css=div[id='tbodyid'] div[class='col-lg-4 col-md-6 mb-4'] div[class='card-block'] h5`;
    this.productImages = `css=div[id='tbodyid'] div[class='col-lg-4 col-md-6 mb-4'] div[class='card h-100'] img`;
    this.productDescriptions = `css=div[id='tbodyid'] div[class='col-lg-4 col-md-6 mb-4'] div[class='card-block'] p`;
  }
}
